### ISSUE TITLE
document the reason for --device=all

### ISSUE THREAD

**Issue by muelli** [flathub/net.mkiol.SpeechNote#38]
I think it would be nice to know why all device access is needed. Not only as a courtesy to the users but also to see in what areas the existing portals are not sufficient.

**Comment by fastrizwaan** [comment]
` --device=all can be used to access devices like controllers or webcams.`

speechnote uses microphone for speech to text recording. would microphone work without --device=all?

**Comment by muelli** [comment]
yes, the sound is managed by pulseaudio, so having this socket is sufficient.
I've just tried to disable --device=all through flatseal and I got the expected result.

**Comment by mkiol** [comment]
Thanks for the question. Indeed, the reason is not documented at all.

Option `--device=all` is to make OpenCL work for AMD ROCm compatible cards. If you are using NVIDIA card or don't need GPU acceleration for Whisper, this option is not needed.

I could instruct AMD users to manually override to `--device=all` but it would be super bad user experience.

**Comment by mkiol** [comment]
Adding for reference: https://github.com/mkiol/dsnote/issues/32 https://github.com/mkiol/dsnote/commit/8259fa7ba19e5bec97f2f82176ac73205ddcae70
